Add flashimage support
Nambers/MiraiCP pull request #110
Opened 2022-01-11 18:34 UTC by Zipper-1

添加对闪照消息的支持

2022-01-11 18:49 UTC, Zipper-1 commented
对于SingleMessage.cpp第105行的构造函数用途我不是特别清楚，但感觉106行有bug，就擅自改动了一下

2022-01-11 18:56 UTC, Antares0982 requested changes
麻烦您在dev分支上进行修改

2022-01-12 08:04 UTC, Nambers approved these changes

2022-01-12 08:42 UTC, merged

2022-01-12 09:10 UTC, Nambers commented
新版本可能没那么快发布, 可以先用这里的 https://github.com/Nambers/MiraiCP-devReleases/tree/main/%23110